export type Styles = {
  cardAside: string;
  cardDateCompact: string;
  cardLabel: string;
  cardLink: string;
  cardMain: string;
  cardTop: string;
  commitTitle: string;
  commitTitleIcon: string;
  commitTitleText: string;
  dashboardHistoryPage: string;
  description: string;
  disclosureButton: string;
  disclosureIcon: string;
  disclosureIconOpen: string;
  emptyCard: string;
  emptyDescription: string;
  emptyTitle: string;
  groupRunCount: string;
  header: string;
  historyCard: string;
  historyGroup: string;
  metaCode: string;
  metaIcon: string;
  metaItem: string;
  metaList: string;
  metaValue: string;
  previousRunCommitTitle: string;
  previousRunCommitTitleIcon: string;
  previousRunCommitTitleText: string;
  previousRunCompareIcon: string;
  previousRunCompareLink: string;
  previousRunItem: string;
  previousRunLink: string;
  previousRunMain: string;
  previousRunMetaCode: string;
  previousRunMetaIcon: string;
  previousRunMetaItem: string;
  previousRunRow: string;
  previousRuns: string;
  previousRunScore: string;
  previousRunsLabel: string;
  previousRunsList: string;
  previousRunsPanel: string;
  repository: string;
  repositoryHeader: string;
  repositoryName: string;
  score: string;
  scoreLabel: string;
  scoreMax: string;
  scorePending: string;
  scoreValue: string;
  scoreValueCritical: string;
  scoreValueExcellent: string;
  scoreValueGood: string;
  scoreValueWarning: string;
  scoreValueWrapper: string;
  summaryItem: string;
  summaryLabel: string;
  summaryList: string;
  summaryValue: string;
  title: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
