services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: frontend_radar
      POSTGRES_USER: frontend_radar
      POSTGRES_PASSWORD: frontend_radar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
