export type Styles = {
  analysisDetailsCard: string;
  badgeGroup: string;
  badgeLine: string;
  checkboxLine: string;
  checkboxPreview: string;
  checkboxText: string;
  checkRow: string;
  compactDetailsCard: string;
  compactList: string;
  compactRowText: string;
  copyActionLine: string;
  disclosureIconLine: string;
  disclosureSummaryLine: string;
  healthScoreCard: string;
  inputControlLine: string;
  inputHintLine: string;
  inputIconLine: string;
  inputLabelLine: string;
  inputPreview: string;
  metaIconLine: string;
  metricMain: string;
  metricMeta: string;
  metricProgressLine: string;
  metricRow: string;
  metricsCard: string;
  metricsList: string;
  progressLine: string;
  recommendationGroups: string;
  recommendationRow: string;
  reportContent: string;
  repositoryAnalysisDescriptionLine: string;
  repositoryAnalysisDescriptionLines: string;
  repositoryAnalysisForm: string;
  repositoryAnalysisHeader: string;
  repositoryAnalysisPanel: string;
  repositoryAnalysisTitleLine: string;
  repositoryDescriptionLine: string;
  repositoryFields: string;
  repositoryMetaItem: string;
  repositoryMetaList: string;
  repositorySummaryCard: string;
  scoreBlock: string;
  scoreDescriptionLine: string;
  scoreLine: string;
  sectionAsideLine: string;
  sectionHeader: string;
  sectionHeaderMain: string;
  sectionLabelRow: string;
  sectionTitleLine: string;
  smallBadgeLine: string;
  sourcesSummaryLine: string;
  status: string;
  statusBadgeLine: string;
  subHeaderIconLine: string;
  subHeaderLine: string;
  submitButtonLine: string;
  toolingGrid: string;
  toolingItem: string;
  toolingItemBody: string;
  toolingSection: string;
  toolingTitleRow: string;
  visualRoot: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
