export const reportScoreCheckIds = [
  'readme',
  'readme-quality',
  'env-example',
  'package-json',
  'test-script',
  'test-files',
  'testing-library',
  'test-coverage',
  'github-actions',
  'ci-pr-trigger',
  'ci-install-step',
  'ci-lint-step',
  'ci-test-step',
  'ci-build-step',
  'ci-project-scope',
  'build-script',
  'lockfile',
  'lockfile-consistency',
  'package-manager',
  'dependency-hygiene',
  'typescript',
  'typescript-config',
  'typescript-strict',
  'typecheck-script',
  'lint-script',
  'linting',
  'formatting',
  'code-health',
  'storybook',
  'bundler',
  'code-splitting',
  'a11y-tooling',
] as const;

export type ReportScoreCheckId = (typeof reportScoreCheckIds)[number];
